apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  REGION: noram
  TIMEZONE: cst
immutable: true
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: busybox:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - configMapRef:
        name: myconfig
  restartPolicy: Never
