apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myds
  namespace: default
  labels:
    app: MYAPP
spec:
  selector:
    matchLabels:
      app: MYAPP
  template:
    metadata:
      labels:
        app: MYAPP
    spec:
      containers:
      - name: myapp
        image: nginx:stable
